---
- name: Force Shutdown All Systems
  hosts: all
  #hosts: rocky_servers     # specific group
  become: true
  #serial: 1 #reboot hosts one by one
  #serial: 2 #reboot 2 hosts at a time

  roles:
    - { role: shutdown_system, when: enable_shutdown }

