ovs_cleanup: true 
ovs_packages: false
ovs_br0: false
ovs_br1: false
ovs_br2: false
ovs_bond: false
ovs_vlans: false
ovs_vlan_interfaces: false
libvirt_qemu_bridge_access: false
libvirt_add_br0_to_KVM: false
libvirt_add_br1_to_KVM: false
libvirt_add_br2_to_KVM: false

ovs_bridges:

  br0:
    enabled: true
    name: br0
    mtu: 1500

    bond:
      name: br0bond0
      mode: active-backup
      uplinks:
        - ens193
        - ens161

    ip_info:
      ip: 192.168.178.35
      prefix: 24
      gateway: 192.168.178.1

      dns:
        - 8.8.8.8
        - 1.1.1.1


  br1:
    enabled: true
    name: br1
    mtu: 9000

    bond:
      name: br1bond1
      mode: lacp
      uplinks:
        - enp3s0
        - enp4s0

      trunks:
        - 151
        - 152
        - 153

    vlans:

      - id: 151
        name: vlan151
        subnet: 172.28.151

      - id: 152
        name: vlan152
        subnet: 172.28.152

      - id: 153
        name: vlan153
        subnet: 172.28.153


  br2:
    enabled: false
    name: br2
    mtu: 9000

    bond:
      enabled: true
      name: br2bond2
      mode: balance-slb
      uplinks:
        - enp5s0
        - enp6s0
