---
# tasks file for roles/cockpit
- name: Install cockpit
  package:
    name: 
      - cockpit
      - cockpit-storaged
      - cockpit-networkmanager 
      - cockpit-packagekit
    state: present

- name: Enable cockpit
  service:
    name: cockpit.socket
    state: started
    enabled: true
