---
# tasks file for roles/ovs_cleanup

- name: Gather existing nmcli connections
  command: nmcli -t -f NAME connection show
  register: nmcli_connections
  changed_when: false

- name: Add NIC with default settings (if br0 exists)
  command: >
    nmcli connection add type ethernet
    ifname {{ ovs_bridges.br0.bond.uplinks[0] }}
    con-name {{ ovs_bridges.br0.bond.uplinks[0] }}
    ipv4.method manual
    ipv4.addresses {{ ovs_bridges.br0.ip_info.ip }}/{{ ovs_bridges.br0.ip_info.prefix }}
    ipv4.gateway {{ ovs_bridges.br0.ip_info.gateway }}
    ipv4.dns "{{ ovs_bridges.br0.ip_info.dns | join(',') }}"
    connection.autoconnect yes mtu {{ ovs_bridges.br0.mtu }}
  when: ovs_bridges.br0.name in nmcli_connections.stdout_lines

- name: Bring up NIC (if br0 exists)
  command: nmcli connection up "{{ ovs_bridges.br0.bond.uplinks[0] }}"
  when: ovs_bridges.br0.name in nmcli_connections.stdout_lines

- name: Set list of base OVS connections to remove
  set_fact:
    ovs_base_connections:
      - "{{ ovs_bridges.br0.name }}"
      - "ovs-port-{{ ovs_bridges.br0.name }}"
      - "ovs-if-{{ ovs_bridges.br0.name }}"
      - "ovs-port-{{ ovs_bridges.br0.bond.name }}"
      - "ovs-{{ ovs_bridges.br0.name }}-if-{{ ovs_bridges.br0.bond.uplinks[0] }}"
      - "ovs-{{ ovs_bridges.br0.name }}-if-{{ ovs_bridges.br0.bond.uplinks[1] }}"
      - "{{ ovs_bridges.br1.name }}"
      - "ovs-port-{{ ovs_bridges.br1.name }}"
      - "ovs-if-{{ ovs_bridges.br1.name }}"
      - "ovs-port-{{ ovs_bridges.br1.bond.name }}"
      - "ovs-{{ ovs_bridges.br1.name }}-if-{{ ovs_bridges.br1.bond.uplinks[0] }}"
      - "ovs-{{ ovs_bridges.br1.name }}-if-{{ ovs_bridges.br1.bond.uplinks[1] }}"
      - "{{ ovs_bridges.br2.name }}"
      - "ovs-port-{{ ovs_bridges.br2.name }}"
      - "ovs-if-{{ ovs_bridges.br2.name }}"
      - "ovs-port-{{ ovs_bridges.br2.bond.name }}"
      - "ovs-{{ ovs_bridges.br2.name }}-if-{{ ovs_bridges.br2.bond.uplinks[0] }}"
      - "ovs-{{ ovs_bridges.br2.name }}-if-{{ ovs_bridges.br2.bond.uplinks[1] }}"

- name: Remove base OVS connections if present
  community.general.nmcli:
    conn_name: "{{ item }}"
    state: absent
  loop: "{{ ovs_base_connections }}"
  when: item in nmcli_connections.stdout_lines

#- name: Remove VLAN ports if present
#  community.general.nmcli:
#    conn_name: "ovs-{{ br1_name }}-port-{{ item.name }}"
#    state: absent
#  loop: "{{ ovs_vlans | default([]) }}"
#  when: "'ovs-' + br1_name + '-port-' + item.name in nmcli_connections.stdout_lines"
#
#- name: Remove VLAN interfaces if present
#  community.general.nmcli:
#    conn_name: "ovs-{{ br1_name }}-if-{{ item.name }}"
#    state: absent
#  loop: "{{ ovs_vlans | default([]) }}"
#  when: "'ovs-' + br1_name + '-if-' + item.name in nmcli_connections.stdout_lines"
