---
admin_user: sysadmin
timezone: Europe/Berlin
update_retry: 2

# Optional feature toggles
report_updates: true         # reporting
enable_cache_cleanup: false
enable_reboot: false         # set true to allow automatic reboot 
enable_hostname: false
