all:
  children:

    debian_servers:
      hosts:
        debian02:
          ansible_host: 192.168.56.100

        #ubuntu01:
        #  ansible_host: 172.28.30.16

        #linumgmt:
        #  ansible_host: 192.168.56.15

        checkmktest:
          ansible_host: 192.168.56.11

    rocky_servers:
      hosts:
        rocky9x:
          ansible_host: 10.0.2.156

    suse_servers:
      hosts:
        node1:
          ansible_host: 10.0.2.154

