all:

  children:

    rocky_servers:
      hosts:
        rocky9x:
          ansible_host: 192.168.178.135
#        rocky01.lab.local:
#          ansible_host: 192.168.178.135
#        rocky02.lab.local:
#          ansible_host: 192.168.178.135

    debian_servers:
      hosts:
#        debian01.lab.local:
#          ansible_host: 192.168.178.135
#        ubuntu01.lab.local:
#          ansible_host: 192.168.178.135

