all:

  children:

    rocky_servers:
      hosts:
        rocky9x:
#        rocky01.lab.local:
#        rocky02.lab.local:

    debian_servers:
      hosts:
#        debian01.lab.local:
#        ubuntu01.lab.local:
