---
- name: Multi-Distro System Update
  hosts: all
  become: true
  roles:
    - { role: cleanup_cache, when: enable_cache_cleanup }
    #- system_update
    #- { role: reboot_system, when: enable_reboot }
