---
# Global Variables

admin_user: sysadmin
admin_shell: /bin/bash

timezone: Europe/Berlin

install_gui: false
#install_gui: true

firewall_services:
  - ssh
  - http
  - https
  - cockpit

base_packages:
  - dmidecode 
  - gpm

vm_guest_tools:
  - open-vm-tools
  - qemu-guest-agent  
  - dmidecode

monitoring_packages:
  - htop
  - iotop
  - iftop
  - lshw
  - sysstat
  - dstat
  - glances

admin_packages:
  - vim
  - nano
  - wget
  - curl
  - git
  - bash-completion
  - screen
  - zip
  - unzip
  - pv
  - lsof

security_network_packages:
  - fail2ban
  - openssl
  - sshguard
  - tcpdump
  - net-tools
  - lldpd
  - bind-utils

storage_tools_packages:
  - lvm2
  - xfsprogs
  - nfs-utils
  - rsync
  - parted
  - lsscsi

snap_packages:
  - simplescreenrecorder
  - asbru

