---

timezone: Europe/Berlin

install_gui: false

firewall_services:
  - ssh
  - http
  - https
  - cockpit

monitoring_packages:
  - htop
  - iotop
  - iftop
  - lshw
  - sysstat
  - dstat
  - glances

admin_packages:
  - vim
  - nano
  - wget
  - curl
  - git
  - bash-completion
  - gpm
  - screen
  - zip
  - unzip
  - pv
  - lsof

security_network_packages:
  - fail2ban
  - openssl
  - sshguard
  - tcpdump
  - net-tools
  - lldpd
  - bind-utils

storage_tools_packages:
  - lvm2
  - xfsprogs
  - nfs-utils
  - rsync
  - parted
  - lsscsi
