---
# tasks file for roles/ovs_br0
- name: Create OVS bridge
  command: nmcli con add type ovs-bridge conn.interface {{ br0_name }} con-name {{ br0_name }}

- name: Create bridge port
  command: nmcli con add type ovs-port conn.interface {{ br0_name }} master {{ br0_name }} con-name ovs-port-{{ br0_name }}

- name: Configure bridge interface
  command: >
    nmcli con add type ovs-interface
    slave-type ovs-port
    conn.interface {{ br0_name }}
    master ovs-port-{{ br0_name }}
    con-name ovs-if-{{ br0_name }}
    ipv4.method manual
    ipv4.addresses {{ br0_ip }}/{{ br0_prefix }}
    ipv4.gateway {{ br0_gw }}
    ipv4.dns {{ br0_dns | join(',') }}
    mtu {{ br0_mtu }}

#Attach Physical Interface to the Bridge
- name: Create OVS port for the interface 
  command: >
    nmcli connection add type ovs-port 
    conn.interface {{ br0_interface1 }}
    master {{ br0_name }}
    con-name ovs-{{ br0_name }}-port-{{ br0_interface1 }}

- name: Attach Physical Interface to the Bridge 
  command: >
    nmcli con add type ethernet
    conn.interface {{ br0_interface1 }}
    master ovs-{{ br0_name }}-port-{{ br0_interface1 }}
    con-name ovs-{{ br0_name }}-if-{{ br0_interface1 }} mtu {{ br0_mtu }}

# Apply and Bring Up Connections
- name: nmcli connection reload 
  command: nmcli connection reload
  ignore_errors: yes

- name: nmcli connection up ovs-{{ br0_name }}-if-{{ br0_interface1 }}
  command: nmcli connection up ovs-{{ br0_name }}-if-{{ br0_interface1 }}
  ignore_errors: yes

- name: nmcli connection up ovs-if-{{ br0_name }}
  command: nmcli connection up ovs-if-{{ br0_name }}
  ignore_errors: yes

# Now remove the old connection safely
#- name: Remove old NIC connection
#  command: nmcli connection delete {{ br0_interface1 }}
#  ignore_errors: yes
