---
# tasks file for ovs_cleanup

# Restore a physical NIC to a clean, default IP configuration
- name: Add NIC with default settings
  command: >
    nmcli connection add type ethernet
    ifname {{ br0_interface1 }}
    con-name {{ br0_interface1 }}
    ipv4.method manual
    ipv4.addresses {{ br0_ip }}/{{ br0_prefix }}
    ipv4.gateway {{ br0_gw }}
    ipv4.dns "{{ br0_dns | join(',') }}"
    connection.autoconnect yes mtu {{ br0_mtu }}
  ignore_errors: no

# Bring up the NIC
- name: Bring up the NIC
  command: nmcli connection up {{ br0_interface1 }}

# Remove bridges
- name: Remove br0 bridge
  command: nmcli connection delete {{ br0_name }}
  ignore_errors: yes

- name: Remove br0 interface
  command: nmcli connection delete ovs-if-{{ br0_name }} ovs-{{ br0_name }}-if-{{ br0_interface1 }} 
  ignore_errors: yes

- name: Remove br0 port
  command: nmcli connection delete ovs-port-{{ br0_name }} ovs-{{ br0_name }}-port-{{ br0_interface1 }}
  ignore_errors: yes


- name: Remove br1 bridge
  command: nmcli connection delete {{ br1_name }}
  ignore_errors: yes

- name: Remove br1 interface
  command: nmcli connection delete ovs-if-{{ br1_name }} ovs-{{ br1_name }}-if-{{ br1_interface1 }}
  ignore_errors: yes

- name: Remove br1 port
  command: nmcli connection delete ovs-port-{{ br1_name }} ovs-{{ br1_name }}-port-{{ br1_interface1 }}
  ignore_errors: yes

# Remove VLAN connections
# Remove VLAN ports
- name: Remove VLAN ports
  command: nmcli connection delete ovs-port-{{ item.name }}
  loop: "{{ ovs_vlans }}"
  ignore_errors: yes


# Remove VLAN interfaces
- name: Remove VLAN interfaces
  command: nmcli connection delete ovs-if-{{ item.name }}
  loop: "{{ ovs_vlans }}"
  ignore_errors: yes
