---
- name: Configure RedHat Systems
  hosts: rocky_servers
  become: true

  roles:
#    - repositories
#    - base_packages
#    - hostname
#    - timezone
#    - ssh
#    - networkmanager
#    - monitoring_tools
#    - admin_tools
#    - admin_user
#    - cockpit
#    - snap
    - vm_guest_tools
    - { role: gui_workstation, when: install_gui }
#    - firewalld
 #   - selinux
#    - force_reboot 
