---
# tasks file for roles/libvirt_add_br1_to_KVM

- name: Get existing libvirt networks
  command: virsh net-list --all --name
  register: libvirt_networks
  changed_when: false

- block:

    - name: Create libvirt XML
      copy:
        dest: /tmp/br1.xml
        content: |
          <network>
            <name>br1</name>
            <forward mode='bridge'/>
            <bridge name='br1'/>
            <virtualport type='openvswitch'/>
          </network>

    - name: Define network
      command: virsh net-define /tmp/br1.xml

    - name: Start network
      command: virsh net-start br1

    - name: Enable autostart
      command: virsh net-autostart br1

  when: "'br1' not in libvirt_networks.stdout_lines"
