---
# tasks file for roles/ovs_vlan_interfaces
- name: Create VLAN ports
  command: >
    nmcli con add type ovs-port
    conn.interface {{ item.name }}
    master {{ br1_name }}
    ovs-port.tag {{ item.id }}
    con-name ovs-{{ br1_name }}-port-{{ item.name }}
  loop: "{{ ovs_vlans }}"

- name: Create VLAN interfaces
  command: >
    nmcli con add type ovs-interface
    slave-type ovs-port
    conn.interface {{ item.name }}
    master ovs-{{ br1_name }}-port-{{ item.name }}
    con-name ovs-{{ br1_name }}-if-{{ item.name }}
    ipv4.method manual
    ipv4.addresses {{ item.subnet }}.{{ node_id }}/24
    mtu {{ br1_mtu }}
  loop: "{{ ovs_vlans }}"
