all:
  children:

    kvm_hosts:
      hosts:

        vml-kvm01-rocky:
          ansible_host: 192.168.178.35

        vml-kvm02-rocky:
          ansible_host: 192.168.178.36

#        kvm03:
#          ansible_host: 192.168.178.37
